### PR TITLE
feat(ui): add git remotes tab

### PR DESCRIPTION
**Pull request by emilaleksanteri**
Complete TODO: Add Git remotes tab #369

### CODE REVIEW

**Review by aymanbagabas — CHANGES_REQUESTED** [review]
Hi @emilaleksanteri, thanks for the PR. This is an oversimplified solution. I think the remotes tab should have each remote act like a directory where you can browse remote branches.

**Comment by emilaleksanteri** [comment]
> Hi @emilaleksanteri, thanks for the PR. This is an oversimplified solution. I think the remotes tab should have each remote act like a directory where you can browse remote branches.

@aymanbagabas so instead of browsing the remotes content on via the existing files and commits tabs etc, have its own thing for those or?

**Comment by aymanbagabas** [comment]
> @aymanbagabas so instead of browsing the remotes content on via the existing files and commits tabs etc, have its own thing for those or?

So instead of listing all the remote branches in one list, use a tree-like structure to browse remote branches. Similar to what Lazygit offers.
image

**Comment by emilaleksanteri** [comment]
> > @aymanbagabas so instead of browsing the remotes content on via the existing files and commits tabs etc, have its own thing for those or?
> 
> So instead of listing all the remote branches in one list, use a tree-like structure to browse remote branches. Similar to what Lazygit offers. image

@aymanbagabas ooh okay, that's really cool, I'll add it to the remote branch feature!

**Pull request closed without merging**
